baseURL = 'https://gallery.nikolovmartin.com/'
locale = 'en-US'
title = 'Martin Nikolov — Photography'
theme = 'digio-theme'

[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'photos'
    pageRef = '/photos'
    weight = 2

  [[menus.main]]
    name = 'videos'
    pageRef = '/videos'
    weight = 3

[module]
  [module.hugoVersion]
    extended = true
    min = '0.123.0'
